import type { NextPage } from "next";
import Head from "next/head";
import { LayoutHome } from "../components/LayoutHome";
import { Header } from "../components/Header";
import { Brand } from "../components/Brand";
import styles from "../styles/Home.module.css";
import { Main } from "../components/Main";
import { Footer } from "../components/Footer/Index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <Header>
          <h1>Header</h1>
        </Header>
        <Main>
          <h1>Main</h1>
        </Main>
        <Footer>
          <h1>Footer</h1>
        </Footer>
      </LayoutHome>
    </>
  );
};

export default Home;
